#!/usr/bin/env bash

# this is a simple config for herbstluftwm
killall herbstclient
killall conky
killall panel.sh
killall lemonbar
killall redshift
killall compton

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
nnnhc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-xfce4-terminal} # use your $TERMINAL with xterm as fallback

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


# tags
tag_names=(    )
tag_keys=(1 2 3 4 5)

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#aa0000'
hc set frame_border_normal_color '#282333' #panel bg color
hc set frame_bg_normal_color '#00aa00'
hc set frame_bg_active_color '#00aa00'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5

hc attr theme.active.color '#eeeeee' #
hc attr theme.normal.color '#aa0000'
hc attr theme.urgent.color orange
hc attr theme.inner_width 2
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#aaaaaa'
hc attr theme.active.outer_color '#aaaaaa'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0



# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors


# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done



# Keyboard speed
xset r rate 240 60 # anywhere between 240-300 is good
xset -b # no annoying beeps
# Dock stuff
#killall cairo-dock  # lmk if you can figure out how to get rid of those
#cairo-dock  &       # anoying blue dots beneath the launchers
hc pad 0 0 0 0  0

hc set focus_follows_mouse 0
#hc pad 0 0 0 0 0

# Misc services

compton --config ~/.config/compton.conf  & # for compositing
feh --bg-center /home/joe/Media/Pictures/uU7Hj5p.jpg &
hc keybind $Mod-d      spawn dmenu_run -h 20 -fn 'Source Code Pro-8' -dim 0  -sb "#ffffff" -nb "#282333" -sf "#282333" -o .9&
#conky -b &

# thinkpad media keys

hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+
hc keybind XF86AudioLowerVolume spawn amixer set Master 5%-
hc keybind XF86AudioMute spawn amixer set Master toggle

hc keybind XF86ScreenSaver spawn slimlock

# cmus shite
#killall cmus-remote
hc keybind $Mod-bracketleft spawn cmus-remote -r #previous
hc keybind $Mod-bracketright spawn cmus-remote -n #next
hc keybind $Mod-equal spawn cmus-remote -u #toggle pause
hc keybind $Mod-minus spawn cmus-remote -s #stop
hc keybind $Mod-slash spawn sh /home/joe/.config/herbstluftwm/c-script.sh

hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
#sshfs

hc keybind $Mod-k spawn run_keybase

sudo umount -l /home/joe/Media/Music/
killall sshfs
sshfs stranger@18.244.7.199:/ -p23 -oIdentityFile=/home/joe/.ssh/id_rsa -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 ~/Media/Music &
xrandr --output VGA1 --off &
xrandr --output LVDS1 --mode 1600x900 &

hc keybind $Mod-apostrophe spawn /home/joe/.config/herbstluftwm/panel-hide.sh

#xautolock -time 5 -locker slimlock &

hc pad 0 20 0 0 0

sudo ip link set enp0s25 down

# t -p ls | head -n -2 |  dmenu  -h 200 -w 400 -fn 'Source Code Pro-8' -dim .5  -sb "#282333" -nb "#282333" -sf "#282333" -o 1 -l 4 -p " "  #idea for displaying todo.sh info on keypress
